spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/curtain?characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: sunday
  redis:
    localhost: localhost
    port: 6379
    database: 7
    password:
    # 过期事件订阅,接收7号数据库中所有key的过期事件
    listen-pattern: __keyevent@7__:expired

rocketmq:
  producer:
    producer-group: CoisiniProducerGroup
  consumer:
    consumer-group: CoisiniConsumerGroup
  namesrv-addr: 127.0.0.1:9876

coisini:
  security:
    jwt-key: coisini
    # 过期时间
    token-expired-in: 86400000
  order:
    # 最大购买数量
    max-sku-limit: 777
    # 1h
    pay-time-limit: 3600
    pay-callback-host: http://talelin.com
    pay-callback-path: /v1/payment/wx/notify



# jpa sql 参数打印
logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: trace
